# -*- coding: utf-8 -*-
"""ganRun.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14LI6eoedSkluXz61cXGdrxD-M637aJYI
"""

from google.colab import drive
drive.mount('/content/gdrive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gdrive/My Drive/tensorFlow
!rm -rf ./cifar10
!git clone https://github.com/hanbuhuai/cifar10.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gdrive/My Drive/tensorFlow/cifar10

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 1.x
import tensorflow as tf
tf.__version__

import os
os.kill(os.getpid(), 9)

!python3 train.py

!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip ngrok-stable-linux-amd64.zip

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gdrive/My Drive/tensorFlow/cifar10/runTime
LOG_DIR = "./train:'train',./test:'test'"
get_ipython().system_raw(
    'tensorboard --logdir {} --host 0.0.0.0 --port 6006 &'
    .format(LOG_DIR)
)
get_ipython().system_raw('./ngrok http 6006 &')
! curl -s http://localhost:4040/api/tunnels | python3 -c "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"